# Generated by Django 4.2.16 on 2026-08-22 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("code", models.CharField(max_length=60)),
                ("name_fa", models.CharField(max_length=255)),
                ("name_en", models.CharField(blank=True, default="", max_length=255)),
                (
                    "subtype",
                    models.CharField(
                        choices=[
                            ("RESIN_MASTERBATCH", "Resin / masterbatch"),
                            ("INK", "Ink (مرکب)"),
                            ("SOLVENT", "Solvent (حلال)"),
                            ("CONSUMABLE", "Consumable"),
                            ("PACKAGING", "Packaging"),
                            ("REGRIND", "Regrind (recycled)"),
                            ("SEMI_FINISHED", "Semi-finished"),
                            ("FINISHED", "Finished"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reorder_point",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
                ),
                (
                    "safety_stock",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
                ),
                (
                    "min_stock",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
                ),
                (
                    "max_stock",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
                ),
                ("lead_time_days", models.PositiveIntegerField(blank=True, null=True)),
                ("shelf_life_days", models.PositiveIntegerField(blank=True, null=True)),
                ("is_hazardous", models.BooleanField(default=False)),
                ("msds_ref", models.CharField(blank=True, default="", max_length=120)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "catalog_material",
                "ordering": ["company", "code"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("code", models.CharField(blank=True, default="", max_length=60)),
                ("name_fa", models.CharField(max_length=255)),
                ("name_en", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "catalog_product",
                "ordering": ["company", "code"],
            },
        ),
        migrations.CreateModel(
            name="ProductClass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("code", models.CharField(max_length=40)),
                ("name_fa", models.CharField(max_length=200)),
                ("name_en", models.CharField(blank=True, default="", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "catalog_product_class",
                "ordering": ["product_type", "code"],
            },
        ),
        migrations.CreateModel(
            name="ProductFamily",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("code", models.CharField(max_length=40)),
                ("name_fa", models.CharField(max_length=200)),
                ("name_en", models.CharField(blank=True, default="", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "catalog_product_family",
                "ordering": ["product_class", "code"],
            },
        ),
        migrations.CreateModel(
            name="ProductGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name_fa", models.CharField(max_length=200)),
                ("name_en", models.CharField(blank=True, default="", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "catalog_product_group",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name_fa", models.CharField(max_length=200)),
                ("name_en", models.CharField(blank=True, default="", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "catalog_product_type",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name_fa", models.CharField(max_length=120)),
                ("name_en", models.CharField(blank=True, default="", max_length=120)),
                (
                    "dimension",
                    models.CharField(
                        choices=[
                            ("COUNT", "Count"),
                            ("LENGTH", "Length"),
                            ("AREA", "Area"),
                            ("MASS", "Mass"),
                            ("VOLUME", "Volume"),
                            ("TIME", "Time"),
                        ],
                        max_length=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "catalog_uom",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="UomConversion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("factor", models.DecimalField(decimal_places=8, max_digits=20)),
            ],
            options={
                "db_table": "catalog_uom_conversion",
            },
        ),
    ]
