# Generated by Django 4.2.16 on 2026-08-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="traceability_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BATCH", "Batch"),
                    ("SERIALIZED_ROLL", "Serialized roll"),
                    ("CARTON", "Carton"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
