# Generated by Django 4.2.16 on 2026-08-22 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("entity_type", models.CharField(db_index=True, max_length=100)),
                ("entity_id", models.CharField(db_index=True, max_length=64)),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, default="", max_length=150)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("checksum_sha256", models.CharField(blank=True, default="", max_length=64)),
                ("storage_key", models.CharField(max_length=512, unique=True)),
                ("description", models.CharField(blank=True, default="", max_length=500)),
            ],
            options={
                "db_table": "documents_attachment",
                "ordering": ["-created_at"],
            },
        ),
    ]
