# Generated by Django 4.2.16 on 2026-08-23 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attachments",
                to="organization.company",
            ),
        ),
    ]
