# Generated by Django 4.2.16 on 2026-08-22 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("employee_code", models.CharField(max_length=40)),
                ("first_name_fa", models.CharField(max_length=120)),
                ("last_name_fa", models.CharField(max_length=120)),
                ("first_name_en", models.CharField(blank=True, default="", max_length=120)),
                ("last_name_en", models.CharField(blank=True, default="", max_length=120)),
                ("job_title", models.CharField(blank=True, default="", max_length=120)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "hr_employee",
                "ordering": ["company", "employee_code"],
            },
        ),
    ]
