# Generated by Django 4.2.16 on 2026-08-22 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Denormalized actor identity, preserved even if the user is removed.",
                        max_length=255,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                            ("CANCEL", "Cancel"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("entity_type", models.CharField(db_index=True, max_length=100)),
                ("entity_id", models.CharField(db_index=True, max_length=64)),
                ("before_state", models.JSONField(blank=True, null=True)),
                ("after_state", models.JSONField(blank=True, null=True)),
                (
                    "correlation_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["-timestamp"],
            },
        ),
    ]
