# Generated by Django 4.2.16 on 2026-08-23 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
        ("audit", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning company for row-level isolation; NULL for platform events (login/logout).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_entries",
                to="organization.company",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["company", "timestamp"], name="audit_log_company_6777e8_idx"
            ),
        ),
    ]
