# Generated by Django 4.2.16 on 2026-08-22 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_material_traceability_mode"),
        ("inventory", "0002_traceabilityunit_stockmovement_genealogylink_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionOutput",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("operation_label", models.CharField(blank=True, default="", max_length=120)),
                ("notes", models.CharField(blank=True, default="", max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outputs",
                        to="production.productionorder",
                    ),
                ),
                (
                    "traceability_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_outputs",
                        to="inventory.traceabilityunit",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_outputs",
                        to="catalog.unitofmeasure",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_outputs",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "production_output",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="MaterialIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("EXPLICIT", "Explicit lot/roll issue"),
                            ("BACKFLUSH", "Backflush"),
                        ],
                        max_length=10,
                    ),
                ),
                ("operation_label", models.CharField(blank=True, default="", max_length=120)),
                ("notes", models.CharField(blank=True, default="", max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_issues",
                        to="catalog.material",
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_issues",
                        to="production.productionorder",
                    ),
                ),
                (
                    "traceability_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_issues",
                        to="inventory.traceabilityunit",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_issues",
                        to="catalog.unitofmeasure",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_issues",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "production_material_issue",
                "ordering": ["created_at", "id"],
            },
        ),
    ]
