# Generated by Django 4.2.16 on 2026-08-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0002_productionoutput_materialissue"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialissue",
            name="routing_operation_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
