# Generated by Django 4.2.16 on 2026-08-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0003_materialissue_routing_operation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialissue",
            name="nonce",
            field=models.UUIDField(
                blank=True,
                default=None,
                help_text="Client-supplied idempotency key — duplicate POSTs with the same nonce are rejected.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="productionoutput",
            name="nonce",
            field=models.UUIDField(
                blank=True,
                default=None,
                help_text="Client-supplied idempotency key — duplicate POSTs rejected.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="materialissue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("nonce__isnull", False)),
                fields=("nonce",),
                name="uq_material_issue_nonce",
            ),
        ),
        migrations.AddConstraint(
            model_name="productionoutput",
            constraint=models.UniqueConstraint(
                condition=models.Q(("nonce__isnull", False)),
                fields=("nonce",),
                name="uq_production_output_nonce",
            ),
        ),
    ]
