# Generated by Django 4.2.16 on 2026-09-03 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_traceabilityunit_stockmovement_genealogylink_and_more'),
        ('catalog', '0003_material_traceability_mode'),
        ('partners', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engineering', '0003_customerproduct_traceability_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reorder_point', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('target_level', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('safety_stock', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('lead_time_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_policies', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planning_policies', to='engineering.customerproduct')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planning_policies', to='catalog.material')),
                ('preferred_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planning_policies', to='partners.supplier')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_policies', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'planning_policy',
                'ordering': ['company', 'warehouse', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='planningpolicy',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('customer_product__isnull', True), ('material__isnull', False)), models.Q(('customer_product__isnull', False), ('material__isnull', True)), _connector='OR'), name='ck_planning_policy_single_item'),
        ),
        migrations.AddConstraint(
            model_name='planningpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('material__isnull', False)), fields=('company', 'warehouse', 'material'), name='uq_planning_policy_company_wh_material'),
        ),
        migrations.AddConstraint(
            model_name='planningpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('customer_product__isnull', False)), fields=('company', 'warehouse', 'customer_product'), name='uq_planning_policy_company_wh_cp'),
        ),
    ]
