# Generated by Django 4.2.16 on 2026-08-22 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_initial"),
        ("inventory", "0002_traceabilityunit_stockmovement_genealogylink_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quality", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityCheckResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("measured_value", models.CharField(max_length=120)),
                (
                    "disposition",
                    models.CharField(
                        choices=[("PASS", "Pass"), ("FAIL", "Fail"), ("HOLD", "Hold / Quarantine")],
                        default="PASS",
                        max_length=5,
                    ),
                ),
                ("checked_at", models.DateTimeField()),
                ("notes", models.CharField(blank=True, default="", max_length=500)),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qc_results",
                        to="hr.employee",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="check_results",
                        to="quality.qualityplanitem",
                    ),
                ),
                (
                    "traceability_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qc_results",
                        to="inventory.traceabilityunit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "quality_check_result",
                "ordering": ["-checked_at"],
            },
        ),
    ]
