# Generated by Django 4.2.16 on 2026-08-22 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=60)),
                ("name_fa", models.CharField(max_length=255)),
                ("name_en", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "engineering_customer_product",
                "ordering": ["company", "code"],
            },
        ),
        migrations.CreateModel(
            name="SpecColor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("sequence", models.PositiveSmallIntegerField()),
                ("color_name", models.CharField(max_length=120)),
                (
                    "coverage_pct",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
                ),
                (
                    "delta_e_tol",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
                ),
            ],
            options={
                "db_table": "engineering_spec_color",
                "ordering": ["revision", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="SpecificationRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("SUPERSEDED", "Superseded"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("change_reason", models.TextField(blank=True, default="")),
                (
                    "spec_format",
                    models.CharField(
                        choices=[
                            ("ROLL_STOCK", "Roll stock (رول)"),
                            ("FINISHED_BAG", "Finished bag (کیسه)"),
                            ("SHEET", "Sheet (ورق)"),
                        ],
                        default="ROLL_STOCK",
                        max_length=16,
                    ),
                ),
                ("bag_type", models.CharField(blank=True, default="", max_length=60)),
                (
                    "width_mm",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "width_tol_low",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "width_tol_high",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "length_mm",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
                ),
                (
                    "length_tol_low",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "length_tol_high",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "gusset_mm",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "print_process",
                    models.CharField(
                        choices=[
                            ("NONE", "No print"),
                            ("FLEXO_SURFACE", "Flexo — surface"),
                            ("FLEXO_REVERSE", "Flexo — reverse"),
                        ],
                        default="NONE",
                        max_length=16,
                    ),
                ),
                ("number_of_colors", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("has_lamination", models.BooleanField(default=False)),
                ("has_cold_seal", models.BooleanField(default=False)),
                (
                    "surface_finish",
                    models.CharField(
                        choices=[("NONE", "None"), ("MATTE", "Matte"), ("GLOSS", "Gloss")],
                        default="NONE",
                        max_length=8,
                    ),
                ),
            ],
            options={
                "db_table": "engineering_specification_revision",
                "ordering": ["root", "revision_number"],
            },
        ),
        migrations.CreateModel(
            name="SpecLayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("sequence", models.PositiveSmallIntegerField()),
                (
                    "function",
                    models.CharField(
                        choices=[
                            ("SUBSTRATE", "Substrate"),
                            ("ADHESIVE", "Adhesive"),
                            ("SEALANT", "Sealant"),
                            ("BARRIER", "Barrier"),
                            ("PRINT", "Print layer"),
                            ("OTHER", "Other"),
                        ],
                        default="SUBSTRATE",
                        max_length=16,
                    ),
                ),
                (
                    "micron",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
                ),
                (
                    "micron_tol_low",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
                ),
                (
                    "micron_tol_high",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
                ),
            ],
            options={
                "db_table": "engineering_spec_layer",
                "ordering": ["revision", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="SpecParameter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("key", models.CharField(max_length=120)),
                (
                    "datatype",
                    models.CharField(
                        choices=[("TEXT", "Text"), ("NUMBER", "Number"), ("BOOL", "Boolean")],
                        default="TEXT",
                        max_length=8,
                    ),
                ),
                ("value_text", models.CharField(blank=True, default="", max_length=500)),
                (
                    "value_number",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
                ),
                ("value_bool", models.BooleanField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, default="", max_length=30)),
                (
                    "tol_low",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
                ),
                (
                    "tol_high",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
                ),
            ],
            options={
                "db_table": "engineering_spec_parameter",
                "ordering": ["revision", "key"],
            },
        ),
        migrations.CreateModel(
            name="ToolingAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("code", models.CharField(max_length=60)),
                ("name_fa", models.CharField(max_length=255)),
                ("name_en", models.CharField(blank=True, default="", max_length=255)),
                (
                    "tooling_type",
                    models.CharField(
                        choices=[
                            ("CLICHE", "Cliché (کلیشه)"),
                            ("SHEET", "Sheet (برگ)"),
                            ("SET", "Set (دست)"),
                        ],
                        default="CLICHE",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("RETIRED", "Retired")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("usage_life_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("notes", models.CharField(blank=True, default="", max_length=500)),
            ],
            options={
                "db_table": "engineering_tooling_asset",
                "ordering": ["company", "code"],
            },
        ),
    ]
