# Generated by Django 4.2.16 on 2026-08-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="routingoperation",
            name="issue_method",
            field=models.CharField(
                blank=True,
                choices=[("EXPLICIT", "Explicit lot/roll issue"), ("BACKFLUSH", "Backflush")],
                max_length=10,
                null=True,
            ),
        ),
    ]
