# Generated by Django 4.2.16 on 2026-08-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allocation",
            name="status",
            field=models.CharField(
                choices=[
                    ("RESERVED", "Reserved"),
                    ("RELEASED", "Released"),
                    ("SHIPPED", "Shipped"),
                ],
                default="RESERVED",
                max_length=10,
            ),
        ),
    ]
