# Generated by Django 4.2.16 on 2026-09-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_alter_allocation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='nonce',
            field=models.UUIDField(blank=True, help_text='Client-supplied idempotency key — duplicate POSTs with the same nonce are rejected.', null=True),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(condition=models.Q(('nonce__isnull', False)), fields=('nonce',), name='uq_shipment_nonce'),
        ),
    ]
