# Generated by Django 4.2.16 on 2026-08-22 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0003_material_traceability_mode"),
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostLayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("unit_cost", models.DecimalField(decimal_places=6, max_digits=18)),
                ("total_cost", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "layer_type",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "Receipt"),
                            ("ISSUE", "Issue"),
                            ("PRODUCTION_OUTPUT", "Production output"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference_type", models.CharField(blank=True, default="", max_length=120)),
                ("reference_id", models.UUIDField(blank=True, null=True)),
                ("po_line_id", models.UUIDField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, default="", max_length=500)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_layers",
                        to="organization.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_layers",
                        to="catalog.material",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "costing_cost_layer",
                "ordering": ["material", "date", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "material", "date"],
                        name="costing_cos_company_3b0449_idx",
                    )
                ],
            },
        ),
    ]
