#!/usr/bin/env bash
# gen-env.sh — generate a production-ready erp/.env with real random secrets.
#
#   ./scripts/gen-env.sh            # create erp/.env (refuses to overwrite)
#   ./scripts/gen-env.sh --force    # regenerate (rotates every secret)
#
# Never commit erp/.env. The generated file is consumed by
# docker-compose.prod.yml (interpolation + env_file) and read by Django.
set -euo pipefail

cd "$(dirname "$0")/.."   # erp/
TARGET=".env"

if [ -f "$TARGET" ] && [ "${1:-}" != "--force" ]; then
    echo "erp/.env already exists — use --force to rotate secrets (restarts are required afterwards)." >&2
    exit 1
fi

# 50+ chars, urlsafe, for DJANGO_SECRET_KEY
DJANGO_SECRET_KEY="$(openssl rand -hex 32)"
POSTGRES_PASSWORD="$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)"

# Default public origin — override with your own before first deploy if needed.
PUBLIC_ORIGIN="${SLZ_PUBLIC_ORIGIN:-https://slz.abystral.kdns.fr}"
PUBLIC_HOST="${SLZ_PUBLIC_HOST:-slz.abystral.kdns.fr}"

cat > "$TARGET" <<EOF
# Generated by scripts/gen-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Do not commit. Rotate: ./scripts/gen-env.sh --force (then restart the stack
# and ALTER the postgres role password — see docs/VPS-DEPLOYMENT-HANDOFF.md).

# --- Django (production) ---
DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
DJANGO_DEBUG=false
DJANGO_SETTINGS_MODULE=config.settings.prod
DJANGO_ALLOWED_HOSTS=$PUBLIC_HOST,localhost,127.0.0.1
DJANGO_LANGUAGE_CODE=fa
DJANGO_TIME_ZONE=Asia/Tehran
LOG_LEVEL=INFO

# --- PostgreSQL ---
POSTGRES_DB=slz_erp
POSTGRES_USER=slz_erp
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
DB_CONN_MAX_AGE=60

# --- Redis / Celery ---
CELERY_BROKER_URL=redis://redis:6379/0
CELERY_RESULT_BACKEND=redis://redis:6379/1
REDIS_CACHE_URL=redis://redis:6379/2

# --- JWT ---
JWT_ACCESS_MINUTES=60
JWT_REFRESH_DAYS=7

# --- API / CORS ---
API_PAGE_SIZE=25
CORS_ALLOWED_ORIGINS=$PUBLIC_ORIGIN
AUTH_THROTTLE_RATE=30/min

# --- Documents ---
DOCUMENTS_MAX_UPLOAD_BYTES=26214400
DOCUMENTS_ALLOWED_EXTENSIONS=pdf,png,jpg,jpeg,svg,ai,xlsx,docx,csv,txt,zip

# --- Production entrypoint behaviour ---
SEED_RBAC_STRICT=true
COLLECT_STATIC=0

# --- Bootstrap superuser (optional; used by seed_rbac) ---
ADMIN_EMAIL=
ADMIN_PASSWORD=
EOF

chmod 600 "$TARGET"
echo "Wrote erp/.env with fresh secrets (600). Public origin: $PUBLIC_ORIGIN"
