# Generated by Django 4.2.16 on 2026-08-23 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
        ("identity", "0002_companymembership"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userrole",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="userrole",
            name="company",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="NULL = global role; set = scoped to this company only.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.company",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userrole",
            unique_together={("user", "role", "company")},
        ),
    ]
